# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
input AMPLIFY {
  globalAuthRule: AuthRule = { allow: public }
} # FOR TESTING ONLY!
type LeftMenu @model {
  id: ID!
  hites: Float!
  moonlitGrove: Float
  hitesSm: Float!
  moonlitGroveSm: Float
  creek: Float!
  silverCurrent: Float
  creekSm: Float!
  silverCurrentSm: Float
  pilot: Float!
  starwatchPeak: Float
  pilotSm: Float!
  starwatchPeakSm: Float
  chinese: Float!
  chineseSm: Float!
  southwest: Float!
  southwestSm: Float!
  green: Float!
  greenSm: Float!
  tuna: Float!
  tunaSm: Float!
  waldorf: Float!
  waldorfSm: Float!
  caesar: Float!
  caesarSm: Float!
  cup: Float!
  bowl: Float!
  foccacia: Float!
  pbj: Float!
  grilledChz: Float!
  hamChz: Float!
  coffee: Float!
  tea: Float!
  chai: Float!
  soupSalad: Float!
}

type CenterMenu @model {
  id: ID!
  halfSandwich: Float!
  ponderosa: Float!
  orchardKeeper: Float
  midpines: Float!
  emberGrove: Float
  midpinesSm: Float!
  emberGroveSm: Float
  captain: Float!
  greenKnight: Float
  captainSm: Float!
  greenKnightSm: Float
  bootjack: Float!
  wayfarer: Float
  bootjackSm: Float!
  wayfarerSm: Float
  fishcamp: Float!
  mariner: Float
  fishcampSm: Float!
  marinerSm: Float
  catheys: Float!
  centurion: Float
  laurel: Float!
  winterCourt: Float
  usona: Float!
  oracle: Float
  grizzly: Float!
  warlock: Float
  grizzlySm: Float!
  warlockSm: Float
  riven: Float!
  alchemist: Float
  rivenSm: Float!
  alchemistSm: Float
  hornitos: Float!
  gunslinger: Float
  totokon: Float!
  artificer: Float
  portal: Float!
  wanderer: Float
  meadows: Float!
  faeryBargain: Float
  meadowsSm: Float!
  faeryBargainSm: Float
  market: Float!
  greenWitch: Float
  mariposan: Float!
  spellbinder: Float
  blt: Float!
  bltSm: Float!
  sourcream: Float!
  hummus: Float!
  avocado: Float!
  pickles: Float!
  bacon: Float!
  fakin: Float!
  extraveg: Float!
  ciabatta: Float!
  croissant: Float!
  sliceChz: Float!
}

type RightMenu @model {
  id: ID!
  mono: Float!
  soloist: Float
  bagby: Float!
  dawnkeeper: Float
  french: Float!
  sunforged: Float
  quiche: Float!
  burritoMeat: Float!
  burritoVeggie: Float!
  bagel: Float!
  creamChz: Float!
  muffin: Float!
  crumblePie: Float!
  chocCake: Float!
  carrotCake: Float!
  brownies: Float!
  cookies: Float!
  juice: Float!
  beetIt: Float!
  crimsonCurrent: Float
  carrotKale: Float!
  greenCircuit: Float
  carrot: Float!
  orangeSpell: Float
  citrus: Float!
  sunward: Float
  pureGreens: Float!
  verdantHex: Float
  smoothie: Float!
  boost: Float!
}