/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ezaavxuusbgc3fhtk3o5r6747a.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-o2sz7qwedbgvnliheybdhfpkba",
    "aws_cognito_identity_pool_id": "us-east-1:6ac2e1f4-442f-48c5-803d-bafa00fea1e3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_dmuXAveOk",
    "aws_user_pools_web_client_id": "6khk9cj5n77tu4sot0v7ek3and",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
